import test from 'node:test'
import assert from 'node:assert/strict'
import {mkdtemp, writeFile, mkdir, rm, chmod, symlink} from 'node:fs/promises'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {execFile} from 'node:child_process'
import {promisify} from 'node:util'
import {gitStatus} from '../lib/git/status.js'
import {gitFiles} from '../lib/git/files.js'
import {gitDiff} from '../lib/git/diff.js'
import {gitCommits} from '../lib/git/commits.js'
import {gitWorkspace} from '../lib/tools/index.js'
import {parseGitRemote} from '../lib/git/repository.js'
const run=promisify(execFile)
async function git(cwd,args){return run('git',args,{cwd,encoding:'utf8'})}
async function fixture(){const cwd=await mkdtemp(join(tmpdir(),'dsh-git-'));await git(cwd,['init','-q']);await git(cwd,['config','user.email','test@example.com']);await git(cwd,['config','user.name','Test']);await writeFile(join(cwd,'file.txt'),'one\n');await git(cwd,['add','file.txt']);await git(cwd,['commit','-qm','initial']);return cwd}
 test('remote parser supports HTTPS, SSH and ssh URL',()=>{for(const [url,owner,repo] of [['https://github.com/a/b.git','a','b'],['git@github.com:a/b.git','a','b'],['ssh://git@github.com/a/b.git','a','b']])assert.deepEqual(parseGitRemote(url),{host:'github.com',owner,repository:repo})})
test('non repository returns structured error',async()=>{const cwd=await mkdtemp(join(tmpdir(),'dsh-nonrepo-'));try{const r=await gitStatus(cwd);assert.equal(r.error.code,'NOT_A_GIT_REPOSITORY')}finally{await rm(cwd,{recursive:true,force:true})}})
test('status, staged, untracked, diff and committed files',async()=>{const cwd=await fixture();try{await writeFile(join(cwd,'file.txt'),'one\ntwo\n');await writeFile(join(cwd,'new file.txt'),'new\n');let r=await gitStatus(cwd);assert.equal(r.files.length,2);assert.equal(r.files.find(x=>x.path==='file.txt').status,'modified');await git(cwd,['add','file.txt']);r=await gitStatus(cwd);assert.equal(r.files.find(x=>x.path==='file.txt').staged,true);const staged=await gitFiles('staged',cwd);assert.equal(staged.files.length,1);const committed=await gitFiles('committed',cwd);assert.deepEqual(committed.files.map(x=>x.path),['file.txt']);const d=await gitDiff({path:'file.txt',staged:true},cwd);assert.equal(d.files[0].additions,1);assert.match(d.files[0].hunks[0].lines.join('\n'),/\+two/);const c=await gitCommits({limit:1},cwd);assert.equal(c.commits[0].message,'initial');const ws=await gitWorkspace(cwd);assert.equal(ws.changes.untracked,1);assert.ok(Array.isArray(ws.files)&&ws.files.some(x=>x.path==='new file.txt'));assert.equal(typeof ws.stashCount,'number');assert.ok(Array.isArray(ws.branches))}finally{await rm(cwd,{recursive:true,force:true})}})
test('malicious diff path is rejected without command execution',async()=>{const cwd=await fixture();try{const r=await gitDiff({path:'--output=/tmp/pwned'},cwd);assert.equal(r.error.code,'INVALID_GIT_ARGUMENT')}finally{await rm(cwd,{recursive:true,force:true})}})
test('renamed and deleted files are classified',async()=>{const cwd=await fixture();try{await git(cwd,['mv','file.txt','renamed.txt']);let r=await gitStatus(cwd);assert.equal(r.files[0].status,'renamed');assert.equal(r.files[0].path,'renamed.txt');assert.equal(r.files[0].oldPath,'file.txt');await git(cwd,['rm','-f','renamed.txt']);r=await gitStatus(cwd);assert.equal(r.files[0].status,'deleted')}finally{await rm(cwd,{recursive:true,force:true})}})
test('workspace numstat covers renames and non-ASCII paths',async()=>{const cwd=await fixture();try{await writeFile(join(cwd,'中文.txt'),'x\n');await git(cwd,['add','中文.txt']);await git(cwd,['commit','-qm','cjk']);await writeFile(join(cwd,'中文.txt'),'x\ny\n');await git(cwd,['mv','file.txt','renamed.txt']);const ws=await gitWorkspace(cwd);const cjk=ws.files.find(x=>x.path==='中文.txt');assert.ok(cjk,'non-ASCII path is not octal-quoted');assert.equal(cjk.status,'modified');assert.equal(cjk.additions,1);assert.equal(cjk.deletions,0);const ren=ws.files.find(x=>x.path==='renamed.txt');assert.ok(ren,'renamed file present');assert.equal(ren.additions,1);assert.equal(ren.deletions,0)}finally{await rm(cwd,{recursive:true,force:true})}})
test('github PR returns explicit no-remote result',async()=>{const cwd=await fixture();try{const {githubPr}=await import('../lib/github/pr.js');const r=await githubPr(cwd);assert.equal(r.error.code,'NO_GITHUB_REMOTE')}finally{await rm(cwd,{recursive:true,force:true})}})
test('github PR parses multiple mocked pull requests',async()=>{const cwd=await fixture();const bin=await mkdtemp(join(tmpdir(),'dsh-gh-'));const gh=join(bin,'gh');try{await git(cwd,['remote','add','origin','git@github.com:owner/repo.git']);await writeFile(gh,'#!/bin/sh\nprintf \'[{"number":1,"title":"one","state":"OPEN","isDraft":false,"baseRefName":"main","headRefName":"master","url":"https://github.com/owner/repo/pull/1"},{"number":2,"title":"two","state":"CLOSED","isDraft":true,"baseRefName":"main","headRefName":"master","url":"https://github.com/owner/repo/pull/2"}]\'\n');await chmod(gh,0o755);const old=process.env.PATH;process.env.PATH=`${bin}:${old}`;try{const {githubPr}=await import('../lib/github/pr.js');const r=await githubPr(cwd);assert.equal(r.pullRequests.length,2);assert.equal(r.pullRequests[1].draft,true)}finally{process.env.PATH=old}}finally{await rm(cwd,{recursive:true,force:true});await rm(bin,{recursive:true,force:true})}})
test('supports Unicode and space filenames plus bounded large diffs',async()=>{const cwd=await fixture();try{const path='空 格.txt';await writeFile(join(cwd,path),'x\n'.repeat(500));const r=await gitDiff({path,limit:5},cwd);assert.equal(r.error,undefined);assert.ok(r.raw.split('\n').length<=5);const files=await gitFiles('working-tree',cwd);assert.equal(files.files.some(x=>x.path===path),true)}finally{await rm(cwd,{recursive:true,force:true})}})
test('detached HEAD and empty workspace are handled',async()=>{const cwd=await fixture();try{await git(cwd,['checkout','--detach','HEAD']);const r=await gitStatus(cwd);assert.equal(r.branch.name,null);assert.equal(r.files.length,0)}finally{await rm(cwd,{recursive:true,force:true})}})
test('upstream ahead and behind fields are numeric',async()=>{const cwd=await fixture();try{const r=await gitStatus(cwd);assert.equal(typeof r.branch.ahead,'number');assert.equal(typeof r.branch.behind,'number');assert.equal(r.branch.upstream,null)}finally{await rm(cwd,{recursive:true,force:true})}})
test('GitHub CLI not installed and unauthenticated are structured errors',async()=>{const cwd=await fixture();const old=process.env.PATH;try{await git(cwd,['remote','add','origin','https://github.com/owner/repo.git']);const empty=await mkdtemp(join(tmpdir(),'dsh-empty-path-'));await symlink('/usr/bin/git',join(empty,'git'));await symlink('/usr/bin/env',join(empty,'env'));process.env.PATH=empty;const {githubPr}=await import('../lib/github/pr.js');let r=await githubPr(cwd);assert.equal(r.error.code,'GH_NOT_INSTALLED');const bin=await mkdtemp(join(tmpdir(),'dsh-gh-auth-'));await symlink('/usr/bin/git',join(bin,'git'));const gh=join(bin,'gh');await writeFile(gh,'#!/bin/sh\necho "You are not logged into any GitHub hosts" >&2\nexit 1\n');await chmod(gh,0o755);process.env.PATH=bin;r=await githubPr(cwd);assert.equal(r.error.code,'GH_NOT_AUTHENTICATED');await rm(bin,{recursive:true,force:true});await rm(empty,{recursive:true,force:true})}finally{process.env.PATH=old;await rm(cwd,{recursive:true,force:true})}})
test('copy detection is represented when Git reports a copied entry',async()=>{const cwd=await fixture();try{await git(cwd,['config','status.renames','copies']);await writeFile(join(cwd,'copy.txt'),'one\n');await git(cwd,['add','copy.txt']);const r=await gitStatus(cwd);assert.ok(['added','copied'].includes(r.files.find(x=>x.path==='copy.txt')?.status));}finally{await rm(cwd,{recursive:true,force:true})}})
test('ahead and behind are reported from a real upstream',async()=>{const root=await mkdtemp(join(tmpdir(),'dsh-upstream-'));const bare=join(root,'origin.git'),a=join(root,'a'),b=join(root,'b');try{await git(root,['init','--bare','-q',bare]);await git(root,['clone','-q',bare,a]);await git(a,['config','user.email','a@example.com']);await git(a,['config','user.name','A']);await writeFile(join(a,'a.txt'),'a\n');await git(a,['add','a.txt']);await git(a,['commit','-qm','a']);await git(a,['push','-qu','origin','master']);await writeFile(join(a,'ahead.txt'),'ahead\n');await git(a,['add','ahead.txt']);await git(a,['commit','-qm','ahead']);let r=await gitStatus(a);assert.equal(r.branch.upstream,'origin/master');assert.equal(r.branch.ahead,1);assert.equal(r.branch.behind,0);await git(root,['clone','-q',bare,b]);await git(b,['config','user.email','b@example.com']);await git(b,['config','user.name','B']);await writeFile(join(b,'behind.txt'),'behind\n');await git(b,['add','behind.txt']);await git(b,['commit','-qm','behind']);await git(b,['push','-q']);await git(a,['fetch','-q','origin']);r=await gitStatus(a);assert.equal(r.branch.ahead,1);assert.equal(r.branch.behind,0)}finally{await rm(root,{recursive:true,force:true})}})
